version: "3.8"

services:
  php:
    build:
      context: ./docker_settings
      dockerfile: Dockerfile_php84
    container_name: php_fpm
    volumes:
      - ./:/var/www/html
      - ./docker_settings/php/php.ini:/usr/local/etc/php/conf.d/php-memory-limit.ini
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./:/var/www/html
      - ./docker_settings/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${NGINX_PORT:-8080}:80
    depends_on:
      - php
    networks:
      - app_network

networks:
  app_network:
    driver: bridge